### ISSUE TITLE
Issue #10: Create issue templates

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#10]
# Motivation

Improve and complete the [community profile](../community)

# Tasks

- [x] Preparation
  - [x] Create [issue label](/ComPriFacNot/ComPriFacNot/issues/labels) "other issue"
- [x] Create [issue templates](/ComPriFacNot/ComPriFacNot/issues/templates/edit)
  - [x] [Bug report](../blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
  - [x] [Feature request](../blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
  - [x] [Other issue](../blob/main/.github/ISSUE_TEMPLATE/other-issue.md)
