### ISSUE TITLE
[OTHER ISSUE]

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#11]
# Context #

- [ ] [Code](/ComPriFacNot/ComPriFacNot)
  - [ ] [GitHub pages](https://comprifacnot.github.io/ComPriFacNot): [*describe*]
  - [ ] Other: [*describe*]
- [ ] [Wiki](/ComPriFacNot/ComPriFacNot/wiki)
  - [ ] Concept(s)
    - [ ] Basics
      - [ ] [English version](/ComPriFacNot/ComPriFacNot/wiki/basics_en)
      - [ ] [German version](/ComPriFacNot/ComPriFacNot/wiki/basics_de)
      - [ ] Other: [*describe*]
    - [ ] Other: [*describe*]
  - [ ] Regulations
    - [ ] [License](/ComPriFacNot/ComPriFacNot/wiki/LICENSE)
    - [ ] [Code of Conduct](/ComPriFacNot/ComPriFacNot/wiki/CODE_OF_CONDUCT)
    - [ ] Other: [*describe*]
  - [ ] Other: [*describe*]
- [x] Management
  - [x] Community: [Create contributing guidelines]
  - [ ] Organization:
    - [ ] [Issue template(s)](/ComPriFacNot/ComPriFacNot/issues/templates/edit):
      - [ ] [Bug report](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
      - [ ] [Feature request](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
      - [ ] [Custom issue](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/custom.md)
      - [ ] Other: [*describe*]
    - [ ] Project(s)/project board(s)/view(s): [*describe*]
    - [ ] Other: [*describe*]
  - [ ] Planning: [*describe*]
  - [ ] Other: [*describe*]
- [ ] Other: [*describe*]

# Motivation/Trigger #

**What triggered this issue?**

- [x] Issue #10 
- [x] Improve/enhance/correct/complete
  - [x] the [community profile](/ComPriFacNot/ComPriFacNot/community)
  - [ ] other: [*describe*]
- [ ] Other: [*describe*]

# Tasks/Steps #

**What are the main tasks/steps?**

- [ ] Preparation
- [ ] Create contributing guidelines
