### ISSUE TITLE
Issue #12: [OTHER] Create a pull request template

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#12]
## Motivation/Trigger ##

**What triggered this issue?**

- ( ) [Discussion about idea ...](../discussions/...)
- (x) Issue #11 
- (x) Improve/enhance/correct/complete
  - (x) the [community profile](/ComPriFacNot/ComPriFacNot/community)
  - ( ) other: [*describe*]
- ( ) Other: [*describe*]

## Context ##

- (x) [Code](/ComPriFacNot/ComPriFacNot)
  - ( ) [GitHub pages](https://comprifacnot.github.io/ComPriFacNot): [*describe*]
  - (x) Other: [Pull-Request-Template]
- ( ) [Wiki](/ComPriFacNot/ComPriFacNot/wiki)
  - ( ) Concept(s)
    - ( ) Basics
      - ( ) [English version](/ComPriFacNot/ComPriFacNot/wiki/basics_en)
      - ( ) [German version](/ComPriFacNot/ComPriFacNot/wiki/basics_de)
      - ( ) Other: [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Regulations
    - ( ) [License](/ComPriFacNot/ComPriFacNot/wiki/LICENSE)
    - ( ) [Code of Conduct](/ComPriFacNot/ComPriFacNot/wiki/CODE_OF_CONDUCT)
    - ( ) Other: [*describe*]
  - ( ) Other: [*describe*]
- (x) Management
  - ( ) Community: [*describe*]
  - ( ) Organization:
    - ( ) [Issue template(s)](/ComPriFacNot/ComPriFacNot/issues/templates/edit):
      - ( ) [Bug report](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
      - ( ) [Feature request](
            /ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
      - ( ) [Custom issue](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/custom.md)
      - ( ) Other: [*describe*]
    - ( ) Project(s)/project board(s)/view(s): [*describe*]
    - (x) Other: [Pull-Request-Template]
  - ( ) Planning: [*describe*]
  - ( ) Other: [*describe*]
- ( ) Other: [*describe*]

## Tasks/Steps ##

**What are the main tasks/steps?**

- [x] Preparation
  - [x] Read documentations
    - [x] [About pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
    - [x] [About collaborative development models](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models)
    - [x] [Creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
    - [x] [About issue and pull request templates](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
- [x] Create [pull request template](../blob/main/.github/pull_request_template.md)
