### ISSUE TITLE
Issue #13: [OTHER] Create new Repo ".github", create "README.md" and move default community health files there

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#13]
## Motivation/Trigger ##

**What triggered this issue?**

- ( ) [Discussion about idea ...](../discussions/...)
- (x) Issues
    - #11
    - #9 
- (x) Improve/enhance/correct/complete
  - ( ) the [community profile](/ComPriFacNot/ComPriFacNot/community)
  - (x) other: [community appearance and maintainability]
- ( ) Other: [*describe*]

## Context ##

- ( ) [Code](/ComPriFacNot/ComPriFacNot)
  - ( ) [GitHub pages](https://comprifacnot.github.io/ComPriFacNot): [*describe*]
  - ( ) Other: [*describe*]
- ( ) [Wiki](/ComPriFacNot/ComPriFacNot/wiki)
  - ( ) Concept(s)
    - ( ) Basics
      - ( ) [English version](/ComPriFacNot/ComPriFacNot/wiki/basics_en)
      - ( ) [German version](/ComPriFacNot/ComPriFacNot/wiki/basics_de)
      - ( ) Other: [*describe*]
    - ( ) Other: [*describe*]
  - (x) Regulations
    - ( ) [License](/ComPriFacNot/ComPriFacNot/wiki/LICENSE)
    - (x) [Code of Conduct](/ComPriFacNot/ComPriFacNot/wiki/CODE_OF_CONDUCT)
    - (x) Other: [All community health files]
  - ( ) Other: [*describe*]
- ( ) Management
  - ( ) Community: [*describe*]
  - ( ) Organization:
    - ( ) [Issue template(s)](/ComPriFacNot/ComPriFacNot/issues/templates/edit):
      - ( ) [Bug report](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
      - ( ) [Feature request](
            /ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
      - ( ) [Custom issue](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/custom.md)
      - ( ) Other: [*describe*]
    - ( ) Project(s)/project board(s)/view(s): [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Planning: [*describe*]
  - ( ) Other: [*describe*]
- ( ) Other: [*describe*]

## Tasks/Steps ##

**What are the main tasks/steps?**

- [x] Create Repo [`.github`](../../.github)
- [x] Adjust Repo [`.github`](../../.github)
  - [x] Disable "Issues"
  - [x] Disable "Packages"
  - [x] Disable "Projects"
  - [x] Disable "Releases"
  - [x] Disable "Wiki"
  - [x] Clone Repo [`.github`](../../.github) to local development environment 
  - [x] Modify [`.github/README.md`](../../.github/blob/main/README.md)
  - [x] Create [`.github/profile/README.md`](../../.github/blob/main/profile/README.md)
- [x] Move community health files from Repo [`ComPriFacNot`](..) to Repo [`.github`](../../.github)
  - [x] [Contributing guidelines](../../.github/blob/main/CONTRIBUTING.md)
  - [x] [Code of Conduct](../../.github/blob/main/CODE_OF_CONDUCT.md)
  - [x] [Pull request template](../../.github/blob/main/pull_request_template.md)
  - [x] [Issue templates](../../.github/tree/main/.github/ISSUE_TEMPLATE)
- [x] Test community health files
