### ISSUE TITLE
Issue #14: [OTHER] Create teams "Guests" and "Contributors" and protect branch "main"

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#14]
## Motivation/Trigger ##

**What triggered this issue?**

- ( ) [Discussion about idea ...](../discussions/...)
- ( ) Issue #...
- ( ) Improve/enhance/correct/complete
  - ( ) the [community profile](/ComPriFacNot/ComPriFacNot/community)
  - ( ) other: [*describe*]
- (x) Other: Prepare groth of community

## Context ##

- ( ) [Code](/ComPriFacNot/ComPriFacNot)
  - ( ) [GitHub pages](https://comprifacnot.github.io/ComPriFacNot): [*describe*]
  - ( ) Other: [*describe*]
- ( ) [Wiki](/ComPriFacNot/ComPriFacNot/wiki)
  - ( ) Concept(s)
    - ( ) Basics
      - ( ) [English version](/ComPriFacNot/ComPriFacNot/wiki/basics_en)
      - ( ) [German version](/ComPriFacNot/ComPriFacNot/wiki/basics_de)
      - ( ) Other: [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Regulations
    - ( ) [License](/ComPriFacNot/ComPriFacNot/wiki/LICENSE)
    - ( ) [Code of Conduct](/ComPriFacNot/ComPriFacNot/wiki/CODE_OF_CONDUCT)
    - ( ) Other: [*describe*]
  - ( ) Other: [*describe*]
- (x) Management
  - (x) Community: Create a team for contributors
  - ( ) Organization:
    - ( ) [Issue template(s)](/ComPriFacNot/ComPriFacNot/issues/templates/edit):
      - ( ) [Bug report](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
      - ( ) [Feature request](
            /ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
      - ( ) [Custom issue](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/custom.md)
      - ( ) Other: [*describe*]
    - ( ) Project(s)/project board(s)/view(s): [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Planning: [*describe*]
  - ( ) Other: [*describe*]
- ( ) Other: [*describe*]

## Tasks/Steps ##

**What are the main tasks/steps?**

- [x] Create team [`Guests`](/orgs/ComPriFacNot/teams/guests)
- [x] Set permissions for team [`Guests`](/orgs/ComPriFacNot/teams/guests)
- [x] Create team [`Contributors`](/orgs/ComPriFacNot/teams/contributors)
- [x] Set permissions for team [`Contributors`](/orgs/ComPriFacNot/teams/contributors)
- [x] Invite new users to team [`Contributors`](/orgs/ComPriFacNot/teams/contributors)
- [x] protect branch `main`
