### ISSUE TITLE
Issue #15: [OTHER] Change community avatar: White background instead of transparent background

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#15]
## Motivation/Trigger ##

**What triggered this issue?**

- ( ) [Discussion about idea ...](../discussions/...)
- ( ) Issue #...
- ( ) Improve/enhance/correct/complete
  - ( ) the [community profile](/ComPriFacNot/ComPriFacNot/community)
  - ( ) other: [*describe*]
- (x) Other: Sent link to community via WhatsApp:

![image](https://user-images.githubusercontent.com/95105802/145393632-54c25250-3758-4c9a-a6ed-acd50c94a007.png)

## Context ##

- ( ) [Code](/ComPriFacNot/ComPriFacNot)
  - ( ) [GitHub pages](https://comprifacnot.github.io/ComPriFacNot): [*describe*]
  - ( ) Other: [*describe*]
- ( ) [Wiki](/ComPriFacNot/ComPriFacNot/wiki)
  - ( ) Concept(s)
    - ( ) Basics
      - ( ) [English version](/ComPriFacNot/ComPriFacNot/wiki/basics_en)
      - ( ) [German version](/ComPriFacNot/ComPriFacNot/wiki/basics_de)
      - ( ) Other: [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Regulations
    - ( ) [License](/ComPriFacNot/ComPriFacNot/wiki/LICENSE)
    - ( ) [Code of Conduct](/ComPriFacNot/ComPriFacNot/wiki/CODE_OF_CONDUCT)
    - ( ) Other: [*describe*]
  - ( ) Other: [*describe*]
- (x) Management
  - ( ) Community: [*describe*]
  - (x) Organization:
    - ( ) [Issue template(s)](/ComPriFacNot/ComPriFacNot/issues/templates/edit):
      - ( ) [Bug report](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
      - ( ) [Feature request](
            /ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
      - ( ) [Custom issue](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/custom.md)
      - ( ) Other: [*describe*]
    - ( ) Project(s)/project board(s)/view(s): [*describe*]
    - (x) Other: Community avatar
  - ( ) Planning: [*describe*]
  - ( ) Other: [*describe*]
- ( ) Other: [*describe*]

## Tasks/Steps ##

**What are the main tasks/steps?**

- [x] Create new avatar with no transparent background
- [x] Wiki: Commit and Push
- [x] Change avatar of community
- [x] Tests
  - [x] via WhatsApp: 
        ![image](https://user-images.githubusercontent.com/95105802/145401504-6172a12b-9acc-41a8-83f9-89ce4a128b55.png)
  - [x] via Signal:
        ![image](https://user-images.githubusercontent.com/95105802/145401663-e5a71570-a64a-4c29-b339-ebf1393b809d.png)
