### ISSUE TITLE
Issue #17: [OTHER] Migrate from JavaScript to TypeScript

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#17]
## Motivation/Trigger ##

**What triggered this issue?**

- ( ) [Discussion about idea ...](../discussions/...)
- (x) Issue #3 
- ( ) Improve/enhance/correct/complete
  - ( ) the [community profile](/ComPriFacNot/ComPriFacNot/community)
  - ( ) other: [*describe*]
- ( ) Other: [*describe*]

## Context ##

- (x) [Code](/ComPriFacNot/ComPriFacNot)
  - (x) [GitHub pages](https://comprifacnot.github.io/ComPriFacNot): [JavaScript-Files]
  - ( ) Other
- ( ) [Wiki](/ComPriFacNot/ComPriFacNot/wiki)
  - ( ) Concept(s)
    - ( ) Basics
      - ( ) [English version](/ComPriFacNot/ComPriFacNot/wiki/basics_en)
      - ( ) [German version](/ComPriFacNot/ComPriFacNot/wiki/basics_de)
      - ( ) Other: [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Regulations
    - ( ) [License](/ComPriFacNot/ComPriFacNot/wiki/LICENSE)
    - ( ) [Code of Conduct](/ComPriFacNot/ComPriFacNot/wiki/CODE_OF_CONDUCT)
    - ( ) Other: [*describe*]
  - ( ) Other: [*describe*]
- ( ) Management
  - ( ) Community: [*describe*]
  - ( ) Organization:
    - ( ) [Issue template(s)](/ComPriFacNot/ComPriFacNot/issues/templates/edit):
      - ( ) [Bug report](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
      - ( ) [Feature request](
            /ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
      - ( ) [Custom issue](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/custom.md)
      - ( ) Other: [*describe*]
    - ( ) Project(s)/project board(s)/view(s): [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Planning: [*describe*]
  - ( ) Other: [*describe*]
- ( ) Other: [*describe*]

## Tasks/Steps ##

**What are the main tasks/steps?**

- Pre-Processing
  - [x] Create new [issue labels](/ComPriFacNot/ComPriFacNot/issues/labels)
    - [x] `github pages`
    - [x] `typescript`
  - [x] Assign labels `github pages` and `typescript` to this issue
  - [x] Learning TypeScript
    - [x] Get Started
      - [x] [TS for JS Programmers](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)
    - [x] Handbook
      - [x] [Intro](https://www.typescriptlang.org/docs/handbook/intro.html)
    - [x] Tutorials
      - [x] [Migrating from JavaScript](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html)
      - [x] [TypeScript compiling with Visual Studio Code](https://code.visualstudio.com/docs/typescript/typescript-compiling)
  - [x] Prepare developer environment
    - [x] [Download](https://nodejs.org/de/) and install NodeJS and npm
    - [x] [Download](https://code.visualstudio.com/docs/typescript/typescript-compiling#_install-the-typescript-compiler) and install the TypeScript compiler
- Processing
  - [x] Migrate from JavaScript to TypeScript
    - [x] Fetch
    - [x] Create local topic-branch `Stefan-Leder-net/issue17`
    - [x] Setting up folders
    - [x] Writing a Configuration File
    - [x] Move JS files to TS folder
    - [x] Rename and adjust JS files to TS
      - [x] `TestCase.ts`
      - [x] `TestRun.ts`
      - [x] `PrimeFactoredInteger.ts`
      - [x] `PrimeFactoredIntegerParser.ts`
      - [x] `PrimeFactoredIntegerFormatter.ts`
      - [x] `PrimeFactoredIntegerTestSuite.ts`
      - [x] `PrimeFactoredIntegerTest.ts`
    - [x] Adjust [`PrimeFactoredIntegerTest.htm`](/ComPriFacNot/ComPriFacNot/blob/main/docs/javascript/PrimeFactoredIntegerTest.htm)
