### ISSUE TITLE
[FEATURE] Create example code for Swift

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#18]
## Motivation/Trigger ##

What triggered this issue?

- ( ) [Discussion about idea ...](../discussions/...)
- ( ) Issue #...
- (x) Other: Private chat

## Current state ##

Is your feature request related to a problem? Please describe.

There is no example code for Swift.

## Desired state ##

Describe the solution you'd like.

Create example code for Swift.

Describe alternatives you've considered.

Example code for other systems/languages.

## Tasks ##

- [ ] Pre-Processing
  - [ ] Assign this issue
  - [ ] Label this issue
  - [ ] Set status of this issue to `in progress`
  - [ ] Create topic branch `Issue-xxx` from `main` branch
  - [ ] Pull topic branch `Issue-xxx`
- [ ] Processing
  - [ ] Create example code for Swift
  - [ ] Test example code for Swift
  - [ ] Commit to local branch `Issue-xxx`
  - [ ] Push to remote branch `Issue-xxx`
- [ ] Post-Processing
  - [ ] Create Pull Request
  - [ ] Assign reviewer
  - [ ] Set status of this issue to `Done`
  - [ ] Close this issue
