### ISSUE TITLE
Issue #20: [OTHER] Wiki: Fix /Sidebar; update Homepage and contributing guide; create folder-footers

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#20]
## Motivation/Trigger ##

**What triggered this issue?**

- ( ) [Discussion about idea ...](../discussions/...)
- (x) Issue #14 
- ( ) Improve/enhance/correct/complete
  - ( ) the [community profile](/ComPriFacNot/ComPriFacNot/community)
  - ( ) other: [*describe*]
- ( ) Other: [*describe*]

## Context ##

- ( ) [Code](/ComPriFacNot/ComPriFacNot)
  - ( ) [GitHub pages](https://comprifacnot.github.io/ComPriFacNot): [*describe*]
  - ( ) Other: [*describe*]
- (x) [Wiki](/ComPriFacNot/ComPriFacNot/wiki)
  - ( ) Concept(s)
    - ( ) Basics
      - ( ) [English version](/ComPriFacNot/ComPriFacNot/wiki/basics_en)
      - ( ) [German version](/ComPriFacNot/ComPriFacNot/wiki/basics_de)
      - ( ) Other: [*describe*]
    - (x) Other:
      - [Homepage](/ComPriFacNot/ComPriFacNot/wiki)
      - [Sidebar](/ComPriFacNot/ComPriFacNot/wiki/_Sidebar.md)
  - (x) Regulations
    - ( ) [License](/ComPriFacNot/ComPriFacNot/wiki/LICENSE)
    - ( ) [Code of Conduct](/ComPriFacNot/ComPriFacNot/wiki/CODE_OF_CONDUCT)
    - (x) Other: [Contributing guide](/ComPriFacNot/ComPriFacNot/wiki/CONTRIBUTING)
  - ( ) Other: [*describe*]
- ( ) Management
  - ( ) Community: [*describe*]
  - ( ) Organization:
    - ( ) [Issue template(s)](/ComPriFacNot/ComPriFacNot/issues/templates/edit):
      - ( ) [Bug report](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
      - ( ) [Feature request](
            /ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/feature_request.md)
      - ( ) [Custom issue](/ComPriFacNot/ComPriFacNot/blob/main/.github/ISSUE_TEMPLATE/custom.md)
      - ( ) Other: [*describe*]
    - ( ) Project(s)/project board(s)/view(s): [*describe*]
    - ( ) Other: [*describe*]
  - ( ) Planning: [*describe*]
  - ( ) Other: [*describe*]
- ( ) Other: [*describe*]

## Tasks/Steps ##

**What are the main tasks/steps?**

- [x] Wiki:
  - [x] [Sidebar](/ComPriFacNot/ComPriFacNot/wiki/_Sidebar.md)
    - [x] Fix link error in renamed avatar
    - [x] Update
  - [x] Update [Homepage](/ComPriFacNot/ComPriFacNot/wiki)
  - [x] Update contributing guide
  - [x] Create folder-footers
  - [x] Commit and push
