### ISSUE TITLE
Issue #22: JavaScript basic integer parser: Enable support for alias digits

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#22]
# Trigger

#3 

# Tasks

- [x] Enable support for alias digits
  - [x] Create file `docs/alias-digits.jsonc` analog to [`docs/basic-digits.jsonc`](/ComPriFacNot/ComPriFacNot/blob/main/docs/basic-digits.jsonc)
  - [x] Extend [`typescript/src/ComPriFacNotConcept.ts`](/ComPriFacNot/ComPriFacNot/blob/main/typescript/src/ComPriFacNotConcept.ts) to support alias digits
  - [x] Extend [`typescript/src/PrimeFactoredIntegerParser.ts`](/ComPriFacNot/ComPriFacNot/blob/main/typescript/src/PrimeFactoredIntegerParser.ts)
  - [x] Extend [`typescript/src/PrimeFactoredIntegerTestSuite.ts`](/ComPriFacNot/ComPriFacNot/blob/main/typescript/src/PrimeFactoredIntegerTestSuite.ts)
