### ISSUE TITLE
[FEATURE] Create code conventions for Swift

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#23]
## Motivation/Trigger ##

What triggered this issue?

- ( ) [Discussion about idea ...](../discussions/...)
- ( ) Issue #
- (x) Other: Pull request #21 

## Current state ##

Is your feature request related to a problem? Please describe.

Every used programming language should have code conventions to ensure a community-wide equal code style and/or look & feel.

## Desired state ##

Describe the solution you'd like.

A code convention for swift is created initally.

Describe alternatives you've considered.

Alternatives were

- not to create code conventions for Swift
- create code conventions later (first begin with concrete programming examples)

## Additional context ##

./.

## Tasks

- [ ] Wiki
  - [ ] Create Swift code conventions in the folder `/regulations/code-conventions` like [JavaScript and TypeScript code conventions](/ComPriFacNot/ComPriFacNot/wiki/JavaScript-and-TypeScript-code-conventions)
  - [ ] Insert Link to Swift code conventions in
    - [ ] [Home](/ComPriFacNot/ComPriFacNot/wiki)
    - [ ] [_Sidebar](/ComPriFacNot/ComPriFacNot/wiki/_Sidebar.md)
    - [ ] [Contributing guidelines](/ComPriFacNot/wiki/CONTRIBUTING)
  - [ ] Commit and push
