### ISSUE TITLE
Issue #27: [FEATURE] GitHub pages: Create favourite icon (x-icon)

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#27]
# Motivation/Trigger #

What triggered this issue?

- ( ) [Discussion about idea ...](../discussions/...)
- (x) Work on issue #22 
- ( ) Other: [*describe*]

# Current state #

Is your feature request related to a problem? Please describe.

The current [GitHub pages](https://comprifacnot.github.io/ComPriFacNot/) don't support favourite icons (x-icons).

So the browsers try to load a favourite icon from the [default common location](https://comprifacnot.github.io/favicon.ico). But there is no default favourite icon. So an error occurres:

![image](https://user-images.githubusercontent.com/95105802/145987305-adc04d3e-0f44-4ae5-ba0a-db51be760412.png)

This disturbs debugging and tracing actions as it is a unnecessary problem.

# Desired state #

Describe the solution you'd like.

A favourite icon should be created and placed on the default location.

Describe alternatives you've considered.

- The use of other existing favourite icons (e. g. the [default GitHub icon](/favicon.ico)) might lead to copyright and/or other legal problems and would create an unnecessary dependency
- The use of "no icon" looks unprofessional

# Additional context #

./.

# Tasks #

- [x] Create a GitHub repository [`ComPriFacNot.github.io`](/ComPriFacNot/ComPriFacNot.github.io) for the community-wide GitHub pages
- [x] Adjust settings of GitHub repository [`ComPriFacNot.github.io`](/ComPriFacNot/ComPriFacNot.github.io)
  - [x] Disable wiki
  - [x] Disable issues
  - [x] Disable projects
  - [x] Enable pages
- [x] Clone GitHub repository [`ComPriFacNot.github.io`](/ComPriFacNot/ComPriFacNot.github.io) locally on developer environment
- [x] Modify GitHub repository [`ComPriFacNot.github.io`](/ComPriFacNot/ComPriFacNot.github.io)
  - [x] Create folder [`/docs`](/ComPriFacNot/ComPriFacNot.github.io/tree/main/docs)
  - [x] Create [favourite icon](/ComPriFacNot/ComPriFacNot.github.io/blob/main/docs/favicon.ico)
  - [x] Create [Homepage](/ComPriFacNot/ComPriFacNot.github.io/blob/main/docs/index.htm)
- [x] Modify GitHub repository [`ComPriFacNot`](/ComPriFacNot/ComPriFacNot)
  - [x] Shorten repo URL from [`https://comprifacnot.github.io/ComPriFacNot/`](https://comprifacnot.github.io/ComPriFacNot/) to [`https://comprifacnot.github.io`](https://comprifacnot.github.io)
- [x] Modify GitHub community [`ComPriFacNot`](/ComPriFacNot)
  - [x] Shorten repo URL from [`https://comprifacnot.github.io/ComPriFacNot/`](https://comprifacnot.github.io/ComPriFacNot/) to [`https://comprifacnot.github.io`](https://comprifacnot.github.io)
