### ISSUE TITLE
Issue #3: feature: JavaScript logic to parse ComPriFacNot basic integers and to convert into decimal numbers

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#3]
[Test page](https://stefan-leder-net.github.io/ComPriFacNot/javascript/PrimeFactoredIntegerTest.htm)

# Tasks# 

- [x] Create test page
- [x] Extend support for new 7 basic digits (see Issue #4) 
- [x] Correct JSDoc
  - [x] [`/docs/javascript/TestCase.js`](../blob/main/docs/javascript/TestCase.js)
  - [x] [`/docs/javascript/PrimeFactoredInteger.js`](../blob/main/docs/javascript/PrimeFactoredInteger.js)
  - [x] [`/docs/javascript/PrimeFactoredIntegerParser.js`](../blob/main/docs/javascript/PrimeFactoredIntegerParser.js)
  - [x] [`/docs/javascript/PrimeFactoredIntegerTestSuite.js`](../blob/main/docs/javascript/PrimeFactoredIntegerTestSuite.js)
- [x] Move concept data from TypeScript to JSON
  - [x] Create file `/docs/basic-digits.jsonc`
  - [x] Modify Parser
- [x] Enable support for new basic digits (see Issue #6)
  - [x] Create Concept class
  - [x] Modify Parser
  - [x] Modify Test Suite
  - [x] Modify `docs/javascript/PrimeFactoredIntegerTest.htm`
