### ISSUE TITLE
Issue #6: Extend basic digits by "ßaäqsöëiýāăćĉēħcķĹnőŗţŧÝŹƁƑÁÅÇÓÿãåéïñûɗɣčɱĕęěĥǏǓǗǛŋȉśŝšȣůŵŻſƅƍЁƙƣƥʑƱйƻщˇǍѣѧ"ǟǧǫҙǷǽԡȋЋ"

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#6]
# Tasks #

- [x] :de: [German concept](../wiki/basics_de) and :uk: [English concept](../wiki/basics_en):
  - [x] extend basic digits by
    - [x] "ß"
    - [x] "a"
    - [x] "ä"
    - [x] "q"
    - [x] "s"
    - [x] "ö"
    - [x] "ë"
    - [x] "i"
    - [x] "ý"
    - [x] "ā"
    - [x] "ă"
    - [x] "ć"
    - [x] "ĉ"
    - [x] "ē"
    - [x] "ħ"
    - [x] "c"
    - [x] "ķ"
    - [x] "Ĺ"
    - [x] "n"
    - [x] "ő"
    - [x] "ŗ"
    - [x] "ţ"
    - [x] "ŧ"
    - [x] "Ý"
    - [x] "Ź"
    - [x] "Ɓ"
    - [x] "Ƒ"
    - [x] "Á"
    - [x] "Å"
    - [x] "Ç"
    - [x] "Ó"
    - [x] "ÿ"
    - [x] "ã"
    - [x] "å"
    - [x] "é"
    - [x] "ï"
    - [x] "ñ"
    - [x] "û"
    - [x] "ɗ"
    - [x] "ɣ"
    - [x] "č"
    - [x] "ɱ"
    - [x] "ĕ"
    - [x] "ę"
    - [x] "ě"
    - [x] "ĥ"
    - [x] "Ǐ"
    - [x] "Ǔ"
    - [x] "Ǘ"
    - [x] "Ǜ"
    - [x] "ŋ"
    - [x] "ȉ"
    - [x] "ś"
    - [x] "ŝ"
    - [x] "š"
    - [x] "ȣ"
    - [x] "ů"
    - [x] "ŵ"
    - [x] "Ż"
    - [x] "ſ"
    - [x] "ƅ"
    - [x] "ƍ"
    - [x] "Ё"
    - [x] "ƙ"
    - [x] "ƣ"
    - [x] "ƥ"
    - [x] "ʑ"
    - [x] "Ʊ"
    - [x] "й"
    - [x] "ƻ"
    - [x] "щ"
    - [x] "ˇ"
    - [x] "Ǎ"
    - [x] "ѣ"
    - [x] "ѧ"
    - [x] "ǟ"
    - [x] "ǧ"
    - [x] "ǫ"
    - [x] "ҙ"
    - [x] "Ƿ"
    - [x] "ǽ"
    - [x] "ԡ"
    - [x] "ȋ"
    - [x] "Ћ"
- [x] Wiki: Commit and push changes
