### ISSUE TITLE
Issue #7: Create a avatar for this org and a social preview card/open graph image for this repo and change org and repo profiles

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#7]
# Tasks #

- [x] Create a ComPriFacNot organization avatar (100 x 100 pixel)
- [x] Change profile of organization ComPriFacNot
- [x] Create a ComPriFacNot repository social preview card/open graph image (1.280 x 640 pixel)
- [x] Change profile of repository ComPriFacNot
- [x] Wiki
  - [x] Edit [`Home.md`](../wiki)
  - [x] Edit [`_Sidebar.md`](../wiki/_Sidebar.md)
  - [x] Commit and push changes
