### ISSUE TITLE
Issue #9: Add "code of conduct"

### ISSUE THREAD

**Issue by Stefan-Leder-net** [ComPriFacNot/ComPriFacNot#9]
# Target

Complete the community profile.

# Tasks

- [x] Preparation
  - [x] Study [Open Source Guide: Your Code of Conduct](https://opensource.guide/code-of-conduct/)
  - [x] Enable 2FA
  - [x] Team [Community leaders](/orgs/ComPriFacNot/teams/community-leaders)
    - [x] Create team
    - [x] Review/assign [team members](/orgs/ComPriFacNot/teams/community-leaders/members)
- [x] Wiki:
  - [x] Create file [`CODE_OF_CONDUCT.md`](../wiki/CODE_OF_CONDUCT)
  - [x] Links from [`Home.md`](../wiki) to [`CODE_OF_CONDUCT.md`](../wiki/CODE_OF_CONDUCT)
  - [x] Links from [`/_Sidebar.md`](../wiki/_Sidebar.md) to [`CODE_OF_CONDUCT.md`](../wiki/CODE_OF_CONDUCT)
  - [x] Commit and push
- [x] Create file [`CODE_OF_CONDUCT.md`](../blob/main/CODE_OF_CONDUCT.md)
- [x] Links from [`CODE_OF_CONDUCT.md`](../blob/main/CODE_OF_CONDUCT.md) to [`wiki/CODE_OF_CONDUCT.md`](../wiki/CODE_OF_CONDUCT)
- [x] Commit and push
